### ISSUE TITLE
開催報告Blog を書いて公開する。

### ISSUE THREAD

**Issue by springaki** [railsgirls-jp/kyoto-team#43]
https://www.tumblr.com/blog/railsgirls-jp に掲載する用。

**Comment by springaki** [comment]
@yulily100 ping.

**Comment by springaki** [comment]
@yulily100 お忙しいのかなー。書けそうかどうかだけ教えてもらってもいいですかー？書けなさそうなら他の人で巻き取れるかどうかなど代替案を検討してみましょう !! :smiley:

**Comment by springaki** [comment]
@torobi が書いてくれるそうなので、権限追加Done. あとは書き上がるのを待つだけ〜。 :sparkles:

**Comment by torobi** [comment]
書いてるのでしばしお待ちを〜:sparkles:

**Comment by springaki** [comment]
Done.
http://blog.railsgirls.jp/post/113156731672/rails-girls-kyoto-2

thanks @torobi
